### ISSUE TITLE
Rover load switch not working

### ISSUE THREAD

**Issue by mavenius** [mavenius/renogy-bt-esphome#16]
@Emerica I grabbed a dump today from the renogy app, so I can see the raw MODBUS commands. 

I did notice that it took a few tries to get the app to turn on the load each time (OFF seemed to be one try each time, but ON was mostly twice and one time it took 4 tries.)

I'll take a peek at the dump in Wireshark ASAP; probably early next week.

**Comment by Emerica** [comment]
```
vector<uint8_t> GetLoadControlRequest(bool turn_on) {
    // MODBUS write single register command
    // Device ID (255), Function Code (6), Register Address (0x010A), Value (0x0001 for on, 0x0000 for off)
    vector<uint8_t> dataBytes = {0xFF, 0x06, 0x01, 0x0A, 0x00, 0x00};  // Register address 0x010A
    
    // Set the value based on turn_on
    if (turn_on) {
        dataBytes[5] = 0x01;  // Value 0x0001 to turn on
        dataBytes.push_back(0x7C);  // CRC LSB
        dataBytes.push_back(0x2A);  // CRC MSB
    } else {
        dataBytes[5] = 0x00;  // Value 0x0000 to turn off
        dataBytes.push_back(0xBD);  // CRC LSB
        dataBytes.push_back(0xEA);  // CRC MSB
    }

    for (size_t i = 0; i < dataBytes.size(); ++i) {
        ESP_LOGD("GetLoadControlRequest", "Request Byte %d: 0x%02X", i, dataBytes[i]);
    }

    return dataBytes;
}

```

Does that work for you?

**Comment by Emerica** [comment]
That is working here again, but maybe I'm missing something if it's CRC values that changed.
It was working before so, seems odd, this appears to be working now.
I had a function that was generating the CRC on the fly but for just off and on it seems better just to optimize by hard coding it.
That's assuming the first bytes don't change, which with that, they don't appear to have.
https://youtube.com/shorts/Ic_dPpO0MNg

**Comment by mavenius** [comment]
The CRC shouldn't change, as the data is the same. I'm taking a look at the raw btsnoop log now to see what's happening, because when I tried again this morning, I had to hit ON twice each time in the Renogy app in order for it to turn on (but OFF only took one attempt each time.)

**Comment by mavenius** [comment]
Well this is interesting... 

I see value 1006010a00016ab5 for ON , 1006010a0000ab75 for off in the btsnoop logs. So it looks like my device ID is 0x10. 

That said, in my experience with the batteries, 0xFF should work for a single device, and the (actual) device ID has to be specified when multiple devices are connected in series. So maybe this is a red herring, because that would mean your code should work. 

I'll add a retry (to turn it on, with a delay between attempts) and see where that gets me.

**Comment by mavenius** [comment]
Interesting... the retry did not help, but updating the device ID from 0xFF to 0x10 did:

```
    vector<uint8_t> dataBytes = {0x10, 0x06, 0x01, 0x0A, 0x00, 0x00};  // Register address 0x010A

    // Set the value based on turn_on
    if (turn_on) {
        dataBytes[5] = 0x01;  // Value 0x0001 to turn on
        // Add hardcoded CRC for turn on command
        dataBytes.push_back(0x6a);  // CRC LSB
        dataBytes.push_back(0xb5);  // CRC MSB
    } else {
        dataBytes[5] = 0x00;  // Value 0x0000 to turn off
        // Add hardcoded CRC for turn off command
        dataBytes.push_back(0xab);  // CRC LSB
        dataBytes.push_back(0x75);  // CRC MSB
    }
```

That's a bummer because in my experience, the device Id isn't predictable.

What's also interesting is that we get the device info using 0xFF...

```
    // charging info
    vector<uint8_t> dataBytes = {255, 3, 1, 0, 0, 34, 209, 241};

```

**Comment by Emerica** [comment]
Is it possibly to query the device id when getting the stats?
That'll change the CRC though too, so maybe the CRC's are ignored?

**Comment by mavenius** [comment]
I don't think the CRC is ignored, as that is part of the MODBUS protocol. I suppose I could try breaking it to confirm, but it's not a big deal to compute on the fly anyway.

I will take another look to see if I can find where the device ID comes from (as the app somehow determined to use the actual device ID instead of 0xFF.) I did look earlier to see what was coming back from our requests to pull the solar data, and it is returning 0xFF in the first byte of those responses.

**Comment by Emerica** [comment]
I was assuming that you had *just* changed the device ID.
What setup do you have, maybe it's actually device related as well and just a lookup in the app.
Rover 20 with a BT-1 here.

**Comment by Emerica** [comment]
![Image](https://github.com/user-attachments/assets/c4143be6-66dc-4a7c-9974-46a11e470c02)

https://www.going-flying.com/blog/files/141/ROVER_MODBUS.pdf

**Comment by mavenius** [comment]
> I was assuming that you had _just_ changed the device ID. What setup do you have, maybe it's actually device related as well and just a lookup in the app. Rover 20 with a BT-1 here.

Got it. I have a Rover 60 with a BT-2, so maybe that's a difference.

**Comment by Emerica** [comment]
When I have it parse out the device id it's 0x11 and substituting that in place of 0xFF on future requests still works.


```
#include <vector>
#include <string>
#include <cmath>
#include <esphome.h>

using namespace std;

// Global variables to store the controller device address and detection status
static uint8_t controller_device_address = 0xFF; // Default to 0xFF until detected
static bool device_id_detected = false;

// Track the last request type (0 for system info, 1 for charging info, 2 for load control, 3 for device address, 4 for full block)
static uint8_t last_request_type = 255; // Invalid default

// Track the last device ID tried for detection
static uint8_t last_device_id = 0xFF;

uint16_t calculate_crc16(const vector<uint8_t>& data, size_t length) {
    uint16_t crc = 0xFFFF;
    for (size_t i = 0; i < length; i++) {
        crc ^= data[i];
        for (int j = 0; j < 8; j++) {
            if (crc & 0x0001) {
                crc >>= 1;
                crc ^= 0xA001;
            } else {
                crc >>= 1;
            }
        }
    }
    return crc;
}

vector<uint8_t> GetRoverRequest(uint8_t request_type) {
    vector<uint8_t> dataBytes;

    last_request_type = request_type; // Store the request type
    if (request_type == 0) { // System Info (registers 0x000C to 0x0013, 8 words)
        dataBytes = {controller_device_address, 3, 0, 12, 0, 8};
        uint16_t crc = calculate_crc16(dataBytes, dataBytes.size());
        dataBytes.push_back(crc & 0xFF); // CRC LSB
        dataBytes.push_back(crc >> 8);   // CRC MSB
        ESP_LOGD("GetRoverRequest", "Requesting System Info with device ID 0x%02X", controller_device_address);
    } else if (request_type == 1) { // Charging Info (registers 0x0100 to 0x0121, 34 words)
        dataBytes = {controller_device_address, 3, 1, 0, 0, 34};
        uint16_t crc = calculate_crc16(dataBytes, dataBytes.size());
        dataBytes.push_back(crc & 0xFF); // CRC LSB
        dataBytes.push_back(crc >> 8);   // CRC MSB
        ESP_LOGD("GetRoverRequest", "Requesting Charging Info with device ID 0x%02X", controller_device_address);
    } else if (request_type == 3) { // Device Address (register 0x001A, 1 word)
        dataBytes = {controller_device_address, 0x03, 0x00, 0x1A, 0x00, 0x01};
        uint16_t crc = calculate_crc16(dataBytes, dataBytes.size());
        dataBytes.push_back(crc & 0xFF); // CRC LSB
        dataBytes.push_back(crc >> 8);   // CRC MSB
        ESP_LOGD("GetRoverRequest", "Requesting Device Address with device ID 0x%02X", controller_device_address);
    }

    for (size_t i = 0; i < dataBytes.size(); ++i) {
        ESP_LOGD("GetRoverRequest", "Request Byte %d: 0x%02X", i, dataBytes[i]);
    }

    return dataBytes;
}

static uint16_t bytes_to_int(const std::vector<uint8_t>& data, size_t offset, size_t length) {
    uint16_t result = 0;
    for (size_t i = 0; i < length; i++) {
        result = (result << 8) | data[offset + i];
    }
    return result;
}

float format_temperature(float celsius, const std::string& unit = "C") {
    if (unit == "F") {
        return (celsius * 9.0f / 5.0f) + 32.0f;
    }
    return celsius;
}

float parse_temperature(uint8_t raw_value, const std::string& unit = "C") {
    int8_t sign = raw_value >> 7;
    float celsius = (sign == 1) ? -(static_cast<float>(raw_value) - 128.0f) : static_cast<float>(raw_value);
    return format_temperature(celsius, unit);
}

void parse_system_info(const vector<uint8_t>& data) {
    ESP_LOGD("parse_system_info", "Received %d bytes", data.size());
    if (data.size() < 19 || data[2] != 0x10) {
        ESP_LOGE("Renogy", "System info data too short: %d bytes, expected byte count 0x10", data.size());
        return;
    }

    // Model String (0x000C to 0x0013, 16 bytes, bytes 3-18)
    string model_string;
    for (size_t i = 3; i < min(data.size(), size_t(19)); i++) {
        if (data[i] >= 0x20 && data[i] <= 0x7E) { // Printable ASCII
            model_string += (char)data[i];
        } else {
            model_string += '.'; // Non-printable placeholder
        }
    }
    while (model_string.length() < 16) {
        model_string += '.';
    }
    id(model_string_sensor).publish_state(model_string.c_str());
    ESP_LOGI("Renogy", "Model String: %s", model_string.c_str());
}

void parse_device_address(const vector<uint8_t>& data) {
    ESP_LOGD("parse_device_address", "Received %d bytes", data.size());
    if (data.size() < 7 || data[2] != 0x02) {
        ESP_LOGE("Renogy", "Device address data too short: %d bytes, expected byte count 0x02", data.size());
        return;
    }

    uint16_t address = bytes_to_int(data, 3, 2);
    controller_device_address = static_cast<uint8_t>(address & 0xFF);
    //device_id_detected = true;
    id(device_address).publish_state(static_cast<float>(controller_device_address));
    ESP_LOGI("Renogy", "Device Address (0x001A): 0x%02X", controller_device_address);
}

void parse_charging_info(const vector<uint8_t>& data) {
    ESP_LOGD("parse_charging_info", "Received %d bytes", data.size());
    if (data.size() < 71) {
        ESP_LOGE("Renogy", "Charging info data too short: %d bytes", data.size());
        return;
    }
    if (data[2] != 0x44) {
        ESP_LOGE("Renogy", "Invalid byte count for charging info: %d", data[2]);
        return;
    }

    id(battery_percentage).publish_state(bytes_to_int(data, 3, 2));
    id(battery_voltage).publish_state(bytes_to_int(data, 5, 2) * 0.1f);
    id(battery_current).publish_state(bytes_to_int(data, 7, 2) * 0.01f);
    id(controller_temperature).publish_state(parse_temperature(data[9]));
    id(battery_temperature).publish_state(parse_temperature(data[10]));
    id(load_voltage).publish_state(bytes_to_int(data, 11, 2) * 0.1f);
    id(load_current).publish_state(bytes_to_int(data, 13, 2) * 0.01f);
    id(load_power).publish_state(bytes_to_int(data, 15, 2));
    id(pv_voltage).publish_state(bytes_to_int(data, 17, 2) * 0.1f);
    id(pv_current).publish_state(bytes_to_int(data, 19, 2) * 0.01f);
    id(pv_power).publish_state(bytes_to_int(data, 21, 2));
    id(max_charging_power_today).publish_state(bytes_to_int(data, 33, 2));
    id(max_discharging_power_today).publish_state(bytes_to_int(data, 35, 2));
    id(charging_amp_hours_today).publish_state(bytes_to_int(data, 37, 2));
    id(discharging_amp_hours_today).publish_state(bytes_to_int(data, 39, 2));
    id(power_generation_today).publish_state(bytes_to_int(data, 41, 2));
    id(power_consumption_today).publish_state(bytes_to_int(data, 43, 2));
    id(power_generation_total).publish_state(bytes_to_int(data, 59, 4) * 0.001f);

    const char* load_status_str = (data[67] & 0x80) ? "on" : "off";
    id(load_status).publish_state(load_status_str);

    const char* charging_status_str;
    switch (data[68]) {
        case 0: charging_status_str = "deactivated"; break;
        case 1: charging_status_str = "activated"; break;
        case 2: charging_status_str = "mppt"; break;
        case 3: charging_status_str = "equalizing"; break;
        case 4: charging_status_str = "boost"; break;
        case 5: charging_status_str = "floating"; break;
        case 6: charging_status_str = "current limiting"; break;
        default: charging_status_str = "unknown"; break;
    }
    id(charging_status).publish_state(charging_status_str);

    ESP_LOGI("Renogy", "Charging data parsed and published");
}

void HandleRoverData(const vector<uint8_t>& data) {
    ESP_LOGD("HandleRoverData", "Processing response of %d bytes", data.size());
    if (data.size() < 5) {
        ESP_LOGE("Renogy", "Data too short: %d bytes", data.size());
        return;
    }

    if (data[1] == 0x03) {
        if (last_request_type == 0) { // System Info
            parse_system_info(data);
        } else if (last_request_type == 1) { // Charging Info
            parse_charging_info(data);
        } else if (last_request_type == 3) { // Device Address
            parse_device_address(data);
        } else {
            ESP_LOGE("Renogy", "Unknown last request type for 0x03: %d", last_request_type);
        }
    } else if (data[1] == 0x06) {
        if (data.size() != 8) {
            ESP_LOGE("Renogy", "Invalid 0x06 response length: %d bytes", data.size());
            return;
        }
        uint16_t crc = calculate_crc16(data, 6);
        if (data[6] != (crc & 0xFF) || data[7] != (crc >> 8)) {
            ESP_LOGE("Renogy", "Invalid CRC in 0x06 response: expected 0x%04X, got 0x%02X%02X",
                     crc, data[7], data[6]);
            return;
        }
        ESP_LOGD("Renogy", "Load control write successful: register 0x%02X%02X, value 0x%02X%02X",
                 data[2], data[3], data[4], data[5]);
    } else {
        ESP_LOGE("Renogy", "Invalid function code: 0x%02X", data[1]);
    }
}

vector<uint8_t> GetLoadControlRequest(bool turn_on) {
    vector<uint8_t> dataBytes = {controller_device_address, 0x06, 0x01, 0x0A, 0x00, static_cast<uint8_t>(turn_on ? 0x01 : 0x00)};
    uint16_t crc = calculate_crc16(dataBytes, dataBytes.size());
    dataBytes.push_back(crc & 0xFF); // CRC LSB
    dataBytes.push_back(crc >> 8);   // CRC MSB
    last_request_type = 2; // Track load control request
    ESP_LOGD("GetLoadControlRequest", "Requesting load control %s with device ID 0x%02X", turn_on ? "ON" : "OFF", controller_device_address);
    for (size_t i = 0; i < dataBytes.size(); ++i) {
        ESP_LOGD("GetLoadControlRequest", "Request Byte %d: 0x%02X", i, dataBytes[i]);
    }
    return dataBytes;
}
```


```

esp32_ble_tracker:
  scan_parameters:
    active: true

text_sensor:
  - platform: template
    name: "Rover Load Status"
    id: load_status
  - platform: template
    name: "Rover Charging Status"
    id: charging_status
  - platform: template
    name: "Rover Model String"
    id: model_string_sensor

sensor:
  - platform: template
    name: "Rover Device Address"
    id: device_address
    unit_of_measurement: ""
    accuracy_decimals: 0
  - platform: template
    name: "Rover Battery Percentage"
    id: battery_percentage
    device_class: battery
    unit_of_measurement: "%"
    accuracy_decimals: 0
  - platform: template
    name: "Rover Battery Voltage"
    id: battery_voltage
    device_class: voltage
    unit_of_measurement: "V"
    accuracy_decimals: 1
  - platform: template
    name: "Rover Battery Current"
    id: battery_current
    device_class: current
    unit_of_measurement: "A"
    accuracy_decimals: 2
  - platform: template
    name: "Rover Battery Temperature"
    id: battery_temperature
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - platform: template
    name: "Rover Controller Temperature"
    id: controller_temperature
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - platform: template
    name: "Rover Load Voltage"
    id: load_voltage
    device_class: voltage
    unit_of_measurement: "V"
    accuracy_decimals: 1
  - platform: template
    name: "Rover Load Current"
    id: load_current
    device_class: current
    unit_of_measurement: "A"
    accuracy_decimals: 2
  - platform: template
    name: "Rover Load Power"
    id: load_power
    device_class: power
    unit_of_measurement: "W"
    accuracy_decimals: 0
  - platform: template
    name: "Rover PV Voltage"
    id: pv_voltage
    device_class: voltage
    unit_of_measurement: "V"
    accuracy_decimals: 1
  - platform: template
    name: "Rover PV Current"
    id: pv_current
    device_class: current
    unit_of_measurement: "A"
    accuracy_decimals: 2
  - platform: template
    name: "Rover PV Power"
    id: pv_power
    device_class: power
    unit_of_measurement: "W"
    accuracy_decimals: 0
  - platform: template
    name: "Rover Max Charging Power Today"
    id: max_charging_power_today
    device_class: power
    unit_of_measurement: "W"
    accuracy_decimals: 0
  - platform: template
    name: "Rover Max Discharging Power Today"
    id: max_discharging_power_today
    device_class: power
    unit_of_measurement: "W"
    accuracy_decimals: 0
  - platform: template
    name: "Rover Charging Amp Hours Today"
    id: charging_amp_hours_today
    unit_of_measurement: "Ah"
    accuracy_decimals: 0
  - platform: template
    name: "Rover Discharging Amp Hours Today"
    id: discharging_amp_hours_today
    unit_of_measurement: "Ah"
    accuracy_decimals: 0
  - platform: template
    name: "Rover Power Generation Today"
    id: power_generation_today
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: "Wh"
    accuracy_decimals: 0
  - platform: template
    name: "Rover Power Consumption Today"
    id: power_consumption_today
    device_class: energy
    unit_of_measurement: "Wh"
    accuracy_decimals: 0
  - platform: template
    name: "Rover Power Generation Total"
    id: power_generation_total
    device_class: energy
    state_class: total_increasing
    unit_of_measurement: "kWh"
    accuracy_decimals: 1
  - platform: ble_client
    ble_client_id: renogy_rover_esp32_bc
    id: renogy_rover_esp32_sensor
    internal: true
    type: characteristic
    service_uuid: FFF0
    characteristic_uuid: FFF1
    notify: true
    update_interval: never
    lambda: |-
      int receivedSize = x.size();
      ESP_LOGD("ble_client_lambda", "Received bytes size: %d", receivedSize);
      for (size_t i = 0; i < receivedSize; ++i) {
        ESP_LOGD("main", "Response Byte %d: 0x%02X", i, x[i]);
      }
      if (receivedSize < 5) return NAN;
      HandleRoverData(x);
      return 0.0;

ble_client:
  - mac_address: ${ble_mac_address}
    name: Renogy Rover
    id: renogy_rover_esp32_bc
    auto_connect: true
    on_connect:
      then:
        - logger.log:
            format: "BLE client connected to rover"
            level: VERBOSE
        - delay: 10s  # Initial delay to allow debugger connection
        - logger.log:
            format: "Starting BLE requests after debug delay"
            level: INFO
        - delay: 2s
        - ble_client.ble_write:
            id: renogy_rover_esp32_bc
            service_uuid: "FFD0"
            characteristic_uuid: "FFD1"
            value: !lambda 'return GetRoverRequest(3);' # Device ID
        - delay: 2s
        - ble_client.ble_write:
            id: renogy_rover_esp32_bc
            service_uuid: "FFD0"
            characteristic_uuid: "FFD1"
            value: !lambda 'return GetRoverRequest(0);' # System Info
    on_disconnect:
      then:
        - logger.log:
            format: "BLE client disconnected from rover"
            level: VERBOSE

interval:
  - interval: 30s
    then:
      - ble_client.ble_write:
          id: renogy_rover_esp32_bc
          service_uuid: "FFD0"
          characteristic_uuid: "FFD1"
          value: !lambda 'return GetRoverRequest(1);' # Charging Info

button:
  - platform: template
    name: "Get Device ID"
    id: get_device_id
    on_press:
      then:
        - logger.log:
            format: "Get Device ID button pressed"
            level: INFO
        - ble_client.ble_write:
            id: renogy_rover_esp32_bc
            service_uuid: "FFD0"
            characteristic_uuid: "FFD1"
            value: !lambda 'return GetRoverRequest(3);' # Device ID
        - delay: 2s

switch:
  - platform: template
    name: "Rover Load Switch"
    id: load_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - ble_client.ble_write:
          id: renogy_rover_esp32_bc
          service_uuid: "FFD0"
          characteristic_uuid: "FFD1"
          value: !lambda 'return GetLoadControlRequest(true);'
      - delay: 2s
    turn_off_action:
      - ble_client.ble_write:
          id: renogy_rover_esp32_bc
          service_uuid: "FFD0"
          characteristic_uuid: "FFD1"
          value: !lambda 'return GetLoadControlRequest(false);'
      - delay: 2s

binary_sensor:
  - platform: ble_presence
    mac_address: ${ble_mac_address}
    name: "Renogy BLE Presence Rover"
    entity_category: diagnostic

```

Does that give you your 0x10?

**Comment by mavenius** [comment]
It's a thing of beauty. Thanks! (It shows 16 in HA, but I get the point :-) )

Want to submit a PR for this?

**Comment by Emerica** [comment]
I'll have to clean it up a little, maybe over the weekend.
Do you get RNG-CTRL-RVR60 ? as a model?

**Comment by mavenius** [comment]
Yep!

RNG-CTRL-ROVER60

Thanks again!

Mark

**Comment by Emerica** [comment]
I've been tied up with things, but at the same time have lost entities twice with this setup. 
Lost about half of them a week ago, reboot of the esp32 all comes back, and today I lost the load status.

**Comment by mavenius** [comment]
@Emerica I've been chasing this situation where entities are lost, and it's not just happening for this integration, but at least one other ESPHome integration that I'm using (although the concept to this one is similar.) 

Reloading the integration does bring the entities back, so I've been doing that so far. It's hard to chase down, given that it seems to happen randomly, and everything works fine when the device initially comes online.

I just now set up a hack that reloads the integration daily... I don't love it, but it will address the problem as long as it happens after > 24 hours:

```
alias: Reload Batteries integration
description: ""
triggers:
  - at: "04:00:00"
    trigger: time
conditions: []
actions:
  - data:
      entry_id: 01JQSCBDA65062NAE27MY6ETMY
    action: homeassistant.reload_config_entry
    alias: Reload batteries integration
  - data:
      entry_id: b3045f0a4b24c4c4db1078679a69ba7f
    action: homeassistant.reload_config_entry
    alias: Reload Renogy rover integration
mode: single
```

Side note that when I implemented this, I wasn't having the issue, so I'm not 100% sure that it actually addresses the issue, but I wanted to put it out there in case it helps you.
